version: '3'

services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "587:587"
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery worker -A mainapp --loglevel=debug --concurrency=4
    volumes:
      - .:/code
    depends_on:
      - redis


  celery-beat:
    build: .
    command: celery -A mainapp beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis

